### ISSUE TITLE
Could not transpile input files: Can't resolve './src' in 'C:\project-dir\' 

### ISSUE THREAD

**Issue by ncgreco1440** [nicojs/angular-stryker-example#5]
I'm trying to base an Angular 6 project on this one and after copying over both the stryker.conf and webpack.conf files over and installing the npm packages I receive the following error which is proving extremely difficult to overcome. 

```
[ERROR] StrykerCli - an error occurred Error: Could not transpile input files: Execute webpack: Error:
ERROR in Entry module not found: Error: Can't resolve './src' in 'C:\project_dir'

**at InitialTestExecutor.<anonymous> (C:\project_dir\node_modules\stryker\src\process\InitialTestExecutor.js:54:31)**
```

My folder structure is like your standard Angular 6 app...

```
/project_dir
   ../node_modules
   ../e2e
   ../src
      ../app
```

I took my package.json and through it into a JSON parser just to confirm that the file wasn't corrupted and it seems to be in working order. 

Here are the versions of stryker/webpack I am working with...

```
"webpack": "4.12.0",
"webpack-cli": "3.0.3",
"stryker": "^0.18.1",
"stryker-api": "^0.12.0",
"stryker-html-reporter": "^0.11.5",
"stryker-karma-runner": "^0.12.0",
"stryker-typescript": "^0.8.3",
"stryker-webpack-transpiler": "^0.1.1",
```

**Comment by nicojs** [comment]
@ncgreco1440 thanks for this issue. I see you've closed it. Does that mean you got it working?

I've added a note to the readme pointing people to the stryker-handbook for angular support (from angular-cli 6.1)

**Comment by ncgreco1440** [comment]
@nicojs I did get it working, as you can see I was using some outdated versions of some of the Stryker packages. I had my company update them to the latest versions, and everything works like a charm!

*knocks on wood*

**Comment by nicojs** [comment]
Awesome! Great to hear.
